### ISSUE TITLE
nginx-full failed to build on 10.10.4

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew-nginx#100]
_From @noff on July 15, 2015 18:36_

Log here: https://gist.github.com/e92909f7a1bcd186711b

Steps:
```
$ brew tap homebrew/nginx
$ brew options nginx-full
$ brew info nginx-full
$ brew install nginx-full --with-perl
```

_Copied from original issue: Homebrew/homebrew#41750_

**Comment by AllenHong007** [comment]
/Applications/Xcode 2.app/Contents/Developer/usr/bin/make -f objs/Makefile install
make: /Applications/Xcode: No such file or directory
make: *** [install] Error 1

**Comment by AllenHong007** [comment]
How to solve this problem？

**Comment by dunn** [comment]
@AllenHong007 that's unrelated.  Try updating Xcode; if that doesn't work, please open a new issue in the main Homebrew repository!

**Comment by denji** [comment]
@AllenHong007 `sudo mv /Applications/Xcode\ 2.app /Applications/Xcode.app`
