### ISSUE TITLE
undefined method `desc' for NginxFull:Class

### ISSUE THREAD

**Issue by wudikua** [Homebrew/homebrew-nginx#106]
sh-3.2# brew install nginx-full
Error: undefined method `desc' for NginxFull:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb:2:in `<class:NginxFull>'
/usr/local/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:131:in `<main>'

**Comment by dunn** [comment]
Running `brew update` should fix it!
