### ISSUE TITLE
Nginx not serving from localhost but will serve from 127.0.0.1

### ISSUE THREAD

**Issue by anthonybrown** [Homebrew/homebrew-nginx#113]
I use `brew-services` and love it but recently I noticed my `nginx` server is no longer serving files from `localhost:8080`    

It will serve from `127.0.0.1:8080`

Any ideas if this has something to do with running everything from `brew-services`?

I've installed all my software with `brew` PHP56, mysql, redis, memcached etc and things were working like expected until a couple of `brew upgrade` ago.

**Comment by anthonybrown** [comment]
Here is the [gist](https://gist.github.com/394d69cfd9be84e2bdbf)

**Comment by plessbd** [comment]
What about your nginx.conf and any enabled sites?
also please provide the output of ```sudo lsof -i TCP -Pn | grep nginx```

I had this happen before and it was because nginx is not listening on ipv4 but only on ipv6

my server directive looks this this:
```
server {
	listen [::]:80;
	return 301 https://$server_name$request_uri;
	include	conf.d/restrictions.conf;
}
```

**Comment by anthonybrown** [comment]
@plessbd I added the `[::]` before the port and it's serving from `localhost` now.
:+1:

**Comment by anthonybrown** [comment]
@plessbd that 301, is that how you serve up PHP applications?
I'd love to be able to not have to use `localhost:8080` for all my `nginx`
projects and just localhost for my `Apache/PHP/MySQL` projects?

**Comment by plessbd** [comment]
@anthonybrown 
If you want more help I can email you (since github as far as I know doesnt let direct communication) and this is a bit off topic

I use a combination of dnsmasq and phpfpm
you can see my setup script here https://github.com/plessbd/setup

I then have nginx have a server_name 
here is an example of my config for adminer

```
server {
	listen [::]:80;
	server_name	adminer.ben.dev;
	return 301 https://$server_name$request_uri;
	include	conf.d/restrictions.conf;
}

server {
	listen       [::]:443 http2 ssl;
	include	conf.d/star.ben.dev.ssl.conf;
	include	conf.d/restrictions.conf;

	server_name	adminer.ben.dev;
	root	/usr/local/share/adminer;

	access_log	/usr/local/etc/nginx/logs/adminer.access.log	json;
	error_log		/usr/local/etc/nginx/logs/adminer.error.log	debug;

	location / {
		# for php
		include	 /usr/local/etc/nginx/conf.d/php-fpm;
	}
}
```

**Comment by anthonybrown** [comment]
@plessbd Thanks, I'll take you up on that offer when I get a little more time, thanks much appreciated!
