### ISSUE TITLE
Compile error – hash-balancing and consistent-hash upstream

### ISSUE THREAD

**Issue by theLordz** [Homebrew/homebrew-nginx#117]
Hello everyone,

I tried multiple solutions, but I couldn't find any solution yet.
If anyone has any idea, please help me.
Console preview: http://pastebin.com/8V3z4XQt

Using El Capitan.

Thank you,
Have a nice day!

**Comment by denji** [comment]
File `/Library/Caches/Homebrew/nginx-full-1.9.7.tar.gz` has size 0?

**Comment by theLordz** [comment]
**Hello and thank you sir for your support.
Indeed with your command and rtmp module, I get that:**

==> Summary
🍺  /usr/local/Cellar/nginx-full/1.9.7_2: 7 files, 1,2M, built in 11 seconds

**Here is the install receipt:**
{"used_options":["--with-rtmp-module"],"unused_options":["--with-passenger","--with-geoip","--without-openssl","--with-libressl","--with-google-perftools","--with-gd","--with-imlib2","--with-no-pool-nginx","--with-addition","--with-auth-req","--with-debug","--with-degredation","--with-flv","--with-gunzip","--with-gzip-static","--with-http2","--with-image-filter","--with-mail","--with-mp4","--with-pcre-jit","--with-perl","--with-random-index","--with-realip","--with-secure-link","--with-spdy","--with-status","--with-stream","--with-sub","--with-webdav","--with-xslt","--with-accept-language-module","--with-accesskey-module","--with-ajp-module","--with-anti-ddos-module","--with-array-var-module","--with-auth-digest-module","--with-auth-ldap-module","--with-auth-pam-module","--with-auto-keepalive-module","--with-autols-module","--with-cache-purge-module","--with-captcha-module","--with-consistent-hash-module","--with-counter-zone-module","--with-ctpp2-module","--with-dav-ext-module","--with-dosdetector-module","--with-echo-module","--with-eval-module","--with-extended-status-module","--with-fancyindex-module","--with-headers-more-module","--with-healthcheck-module","--with-http-accounting-module","--with-http-flood-detector-module","--with-http-remote-passwd-module","--with-log-if-module","--with-lua-module","--with-mod-zip-module","--with-mogilefs-module","--with-mp4-h264-module","--with-naxsi-module","--with-notice-module","--with-php-session-module","--with-push-stream-module","--with-realtime-req-module","--with-redis-module","--with-redis2-module","--with-set-misc-module","--with-small-light-module","--with-subs-filter-module","--with-tcp-proxy-module","--with-txid-module","--with-unzip-module","--with-upload-module","--with-upload-progress-module","--with-upstream-hash-module","--with-upstream-order-module","--with-ustats-module","--with-var-req-speed-module","--with-websockify-module","--with-xsltproc-module"],"built_as_bottle":false,"poured_from_bottle":false,"time":1447950706,"HEAD":"4d309c9199de18f924be19486e8552ce159c94e6","stdlib":null,"compiler":"clang","source":{"path":"/usr/local/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb","tap":"homebrew/homebrew-nginx","spec":"devel"}}

**Well, it seems the command I used to build nginx was not good.**
*(brew install nginx-full --with-cache-purge-module --with-consistent-hash-module --with-debug --with-flv --with-gd --with-geoip --with-gunzip --with-gzip-static --with-headers-more-module --with-healthcheck-module --with-image-filter --with-mail --with-mp4 -with-mp4-h264-module --with-push-stream-module --with-realip --with-redis-module --with-rtmp-module --with-secure-link --with-stream --with-upload-module --with-upload-progress-module --with-upstream-hash-module --with-upstream-order-module --devel)*

**I will try tonight to rebuild nginx by adding arguments one by one and see which one is the cause of the problem and I'll report it back. **

**Comment by theLordz** [comment]
Ok. Fortunately this task wasn't so time consuming.

**There are 2 modules giving errors (with devel arg or not, OS X 10.11.1):**
1. --with-healthcheck-module
2. --with-upstream-hash-module

**Healthcheck module error**
appdev$ brew uninstall nginx-full
Uninstalling /usr/local/Cellar/nginx-full/1.9.7_2... (7 files, 1,0M)
appdev$ brew install nginx-full --with-cache-purge-module --with-consistent-hash-module --with-debug --with-flv --with-gd --with-geoip --with-gunzip --with-gzip-static --with-headers-more-module --with-image-filter --with-healthcheck-module --devel
==> Installing nginx-full from homebrew/homebrew-nginx
==> Downloading http://nginx.org/download/nginx-1.9.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/nginx-full-1.9.7.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.9.7_2 --with-http_ssl_module --with-pcre --with-ipv6 --sbin-path=/u
==> make install
Last 15 lines from /Users/appdev/Library/Logs/Homebrew/nginx-full/02.make:
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/usr/local/share/healthcheck-nginx-module/ngx_http_healthcheck_module.c:753:42: error: no member named 'health_buffersize' in 'struct ngx_http_upstream_srv_conf_s'
          ngx_http_healthchecks[i].conf->health_buffersize);
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/usr/local/share/healthcheck-nginx-module/ngx_http_healthcheck_module.c:823:51: error: no member named 'healthcheck_enabled' in 'struct ngx_http_upstream_srv_conf_s'
        return ngx_http_healthchecks[index].conf->healthcheck_enabled &&
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/usr/local/share/healthcheck-nginx-module/ngx_http_healthcheck_module.c:1003:11: error: no member named 'healthcheck_enabled' in 'struct ngx_http_upstream_srv_conf_s'
    uscf->healthcheck_enabled = 1;
    ~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [objs/addon/healthcheck-nginx-module/ngx_http_healthcheck_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

__________________________________________________________________________________________________________________________________________
**Upstream hash module error**
appdev$ brew install nginx-full --with-cache-purge-module --with-consistent-hash-module --with-debug --with-flv --with-gd --with-geoip --with-gunzip --with-gzip-static --with-headers-more-module --with-image-filter --with-mail --with-mp4 --with-mp4-h264-module --with-push-stream-module --with-realip --with-redis-module --with-rtmp-module --with-secure-link --with-stream --with-upload-module --with-upload-progress-module --with-upstream-hash-module --devel
==> Installing nginx-full from homebrew/homebrew-nginx
==> Downloading http://nginx.org/download/nginx-1.9.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/nginx-full-1.9.7.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.9.7_2 --with-http_ssl_module --with-pcre --with-ipv6 --sbin-path=/u
==> make install
Last 15 lines from /Users/appdev/Library/Logs/Homebrew/nginx-full/02.make:
	objs/addon/dash/ngx_rtmp_dash_module.o \
	objs/addon/hls/ngx_rtmp_mpegts.o \
	objs/addon/dash/ngx_rtmp_mp4.o \
	objs/addon/upload-nginx-module/ngx_http_upload_module.o \
	objs/addon/upload-progress-nginx-module/ngx_http_uploadprogress_module.o \
	objs/addon/upstream-hash-nginx-module/ngx_http_upstream_hash_module.o \
	objs/ngx_modules.o \
	-L/usr/local/lib -L/usr/local/Cellar/pcre/8.37/lib -L/usr/local/Cellar/openssl/1.0.2d_1/lib -lpcre -lssl -lcrypto -lz -lgd -lGeoIP
duplicate symbol _ngx_http_upstream_hash_module in:
    objs/src/http/modules/ngx_http_upstream_hash_module.o
    objs/addon/upstream-hash-nginx-module/ngx_http_upstream_hash_module.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [objs/nginx] Error 1
make: *** [install] Error 2

**Builded successfully without these two modules.**
Maybe if anyone can confirm in order to fix these issues.

**Comment by denji** [comment]
* upstream hash, can delete it there with nginx 1.7.2+
  http://nginx.org/en/docs/http/ngx_http_upstream_module.html#hash

* healthcheck-module is not very stable at the moment
  https://github.com/yaoweibin/nginx_upstream_check_module/issues

If you are willing to rectify the situation we will accept pull request, but first send patches to upstream.
