### ISSUE TITLE
13: Pemission denied in /usr/local/var/sun/nginx/client_body_temp

### ISSUE THREAD

**Issue by hinok** [Homebrew/homebrew-nginx#124]
System info
```
OS X 10.11.2
nginx 1.8.0
```

Today I got the following error in nginx logs while uploading a file:

```
2015/12/23 13:59:52 [crit] 53621#0: *2 open() "/usr/local/var/run/nginx/client_body_temp/0000000001" failed (13: Permission denied), client: 127.0.0.1 
// rest of logs...
```

I've googled a bit and finally found a solution which works.
The folder `var` wasn't executable (only `drwx------`), so I changed it

```
sudo chmod o+x /usr/local/var
```

I've also changed user to `nobody` (earlier set to my local user), but I still don't know whether it was causing the problem or not. I think that `chmod o+x` fixes the problem.

```
sudo chown -vhR nobody:admin /usr/local/var/run/nginx
```

Could this issue be fixed directly in the formula or it was the problem with my env configuration?

**Comment by denji** [comment]
sudo chown -vhR $USER:admin /usr/local/var/run/nginx

**Comment by hinok** [comment]
@denji I'm pretty sure that `chown -vhR` didn't help in my case.
I did it firstly but it wasn't working. Later I executed `chmod o+x` and it fixed the problem in my case.
I wasn't sure whether the last command or combination of both commands solved the problem.

Look that I have following permissions:
```
$ tree -ug /usr/local/var/run/
/usr/local/var/run/
├── [nobody   admin   ]  nginx
│   ├── [nobody   admin   ]  client_body_temp [error opening dir]
│   ├── [nobody   admin   ]  fastcgi_temp [error opening dir]
│   ├── [nobody   admin   ]  proxy_temp [error opening dir]
│   ├── [nobody   admin   ]  scgi_temp [error opening dir]
│   └── [nobody   admin   ]  uwsgi_temp [error opening dir]
└── [root     admin   ]  nginx.pid

6 directories, 1 file
```

and everything works fine.

**Comment by denji** [comment]
nginx running (root)?

**Comment by hinok** [comment]
I launch nginx in this way (nginx listens on 80 port)

```
$ sudo cp /usr/local/opt/nginx/*.plist /Library/LaunchDaemons
$ sudo launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
```

Source: http://derickbailey.com/2014/12/27/how-to-start-nginx-on-port-80-at-mac-osx-boot-up-log-in/

**Comment by denji** [comment]
```bash
sudo chown -vhR root:admin /usr/local/var/run/nginx
sudo chmod -vR 700 /usr/local/var/run/nginx/*_temp
```

**Comment by sukeerthiadiga** [comment]
In my case client request body supposed to be buffered to a temporary file. This is what I did.

```
sudo chmod o+x /usr/local/var
sudo chown -vhR nobody:admin /usr/local/var/run/nginx
```

**Comment by MaxGabriel** [comment]
I just ran into this issue. I know there are workarounds, but does anyone know what the root cause of this is? Both mine and my coworker's Mac have these files owned by `nobody`

**Comment by denissdubinin** [comment]
I stopped nginx and started it with sudo - this helped me
