### ISSUE TITLE
shared memory zone "push_module" was locked by 13877 救命啊！

### ISSUE THREAD

**Issue by abattle** [Homebrew/homebrew-nginx#127]
I have no idea about this mistake.
2015/12/29 14:23:58 [alert] 6625#0: worker process 13877 exited on signal 11
2015/12/29 14:23:58 [alert] 6625#0: shared memory zone "push_module" was locked by 13877
2015/12/29 14:23:58 [alert] 6625#0: worker process 13906 exited on signal 11
2015/12/29 14:23:58 [alert] 6625#0: shared memory zone "push_module" was locked by 13906
2015/12/29 14:23:58 [alert] 6625#0: worker process 13905 exited on signal 11
2015/12/29 14:23:58 [alert] 6625#0: shared memory zone "push_module" was locked by 13905
2015/12/29 14:23:59 [alert] 6625#0: worker process 13917 exited on signal 11
2015/12/29 14:23:59 [alert] 6625#0: shared memory zone "push_module" was locked by 13917
2015/12/29 14:24:03 [alert] 6625#0: worker process 13938 exited on signal 11
2015/12/29 14:24:03 [alert] 6625#0: shared memory zone "push_module" was locked by 13938

**Comment by denji** [comment]
3rd modules, write the developer of the module https://github.com/wandenberg/nginx-push-stream-module/issues
