### ISSUE TITLE
./auto/configure: error: invalid option "--with-http_spdy_module"

### ISSUE THREAD

**Issue by noscripter** [Homebrew/homebrew-nginx#146]
I'm running this command to install nginx-full:

`brew install nginx-full --with-upload-module --HEAD --with-spdy --with-http2 --with-google-perftools --with-anti-ddos-module --with-debug --with-dosdetector-module --with-geoip`

and get the error as the title says: `./auto/configure: error: invalid option "--with-http_spdy_module"`.

**Comment by denji** [comment]
@noscripter All functions spdy now moved to http2 module.

**Comment by noscripter** [comment]
@denji  thank you, that's compliant with the progress of http2, thanks guys.
