### ISSUE TITLE
Issue when installing with modules

### ISSUE THREAD

**Issue by 2color** [Homebrew/homebrew-nginx#163]
I'm trying to install nginx with the `subs-filter-module`

After installing it I'm getting `nginx: [emerg] unknown directive "sub_filter" in /usr/local/etc/nginx/servers/myserver.conf:11`

```
➜  ~ brew uninstall nginx-full --with-subs-filter-module
Uninstalling /usr/local/Cellar/nginx-full/1.8.1... (7 files, 948.4K)
➜  ~ brew install nginx-full --with-subs-filter-module
==> Installing nginx-full from homebrew/nginx
==> Downloading http://nginx.org/download/nginx-1.8.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/nginx-full-1.8.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.8.1 --with-http_ssl_module --with-pcre --with-ipv6 --sbin-path
```

It seems to me that the `./configure` command isn't taking the third party module options into consideration. 

Am I missing something here?

**Comment by denji** [comment]
* [`--with-subs-filter-module`](https://github.com/yaoweibin/ngx_http_substitutions_filter_module) – nginx_substitutions_filter [3rd Party Modules](https://www.nginx.com/resources/wiki/modules/substitutions/) - a filter module which can do both regular expression and fixed string substitutions on response bodies. This module is quite different from the NGINX’s native Substitution Module. It scans the output chains buffer and matches string line by line, just like Apache’s mod_substitute.
* [`--with-sub`](http://nginx.org/en/docs/http/ngx_http_sub_module.html) – ngx_http_sub_module module is a filter that modifies a response by replacing one specified string by another.

**Comment by 2color** [comment]
Thanks @denji
