### ISSUE TITLE
[question] Change the default config file path

### ISSUE THREAD

**Issue by flashios09** [Homebrew/homebrew-nginx#235]
Hi,

Is it possible to change the default config file path from `/usr/local/etc/nginx/nginx.conf` to `/etc/nginx/nginx.conf`, i tried `nginx -c /etc/nginx/nginx.conf` but when i redo `nginx -V` it always says that the default conf file path is `--conf-path=/usr/local/etc/nginx/nginx.conf`

Thanks

**Comment by denji** [comment]
You could, with the existence of "/etc/nginx/"

    sudo ln -sf "/usr/local/etc/nginx/nginx.conf" "/etc/nginx/nginx.conf"

But it is bad practice for ArchLinux, MacOS & BSD* based distribution.

**Comment by denji** [comment]
I'm closing this issue

**Comment by flashios09** [comment]
@denji I know the *symlink* solution (i'm using it), i want a *config* solution(if exists)

**Comment by rlamorea** [comment]
...and yet if I'm reading correctly the last change to the openresty brew formula removed the args that set the default config file location entirely.  What's up with that?

**Comment by denji** [comment]
@rlamorea Homebrew/homebrew-nginx#244
