### ISSUE TITLE
openresty cannot be started without `sudo`?

### ISSUE THREAD

**Issue by ghprince** [Homebrew/homebrew-nginx#243]
```
% brew info openresty
homebrew/nginx/openresty: stable 1.11.2.2
Scalable Web Platform by Extending NGINX with Lua
http://openresty.org
/usr/local/Cellar/openresty/1.11.2.2 (260 files, 5.4M) *
  Built from source on 2017-01-07 at 14:36:44
From: https://github.com/Homebrew/homebrew-nginx/blob/master/Formula/openresty.rb
==> Dependencies
Required: pcre ✔, openssl ✔
Optional: postgresql ✘, geoip ✘
==> Options
--with-debug
	Compile with support for debug logging but without proper gdb debugging symbols
--with-geoip
	Compile with ngx_http_geoip_module
--with-gunzip
	Compile with ngx_http_gunzip_module
--with-iconv
	Compile with support for converting character encodings
--with-postgresql
	Compile with support for direct communication with PostgreSQL database servers
--with-slice
	Compile with ngx_http_slice_module
--with-stub_status
	Compile with ngx_http_stub_status_module
--with-webdav
	Compile with ngx_http_dav_module
--without-ipv6
	Compile *without* support for IPv6
--without-luajit
	Compile *without* support for the Lua Just-In-Time Compiler
==> Caveats
To have launchd start homebrew/nginx/openresty now and restart at login:
  brew services start homebrew/nginx/openresty
Or, if you don't want/need a background service you can just run:
  openresty
% openresty
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

If I run `sudo openresty`, it will start without issue. But I think the whole point of Homebrew is to be able to run services without `root` permission

**Comment by denji** [comment]
Without tuning `net.inet.ip.portrange.*` you will not be able to run the application on port :80 from unprivileged user.

```sh
$ sysctl net.inet.ip.portrange
```

**Comment by denji** [comment]
> However, Unix-like operating system by default do not allow programs that run non-root to listen on TCP/IP ports <1024.

Without tuning `net.inet.ip.portrange.*` you will not be able to run the application on port `:80` from __unprivileged user__. You can omit the benefits from the workflow, so only nginx can require root privileges, but the child processes do not require root rights.

```sh
$ sysctl net.inet.ip.portrange
```

* https://www.nginx.com/blog/inside-nginx-how-we-designed-for-performance-scale/

**Comment by denji** [comment]
> However, Unix-like operating system by default do not allow programs that run non-root to listen on TCP/IP ports <1024.

Without tuning `net.inet.ip.portrange.*` you will not be able to run the application on port `:80` from __unprivileged user__. You can omit the benefits from the workflow, so only nginx can require root privileges, but the child processes do not require root permission.

```sh
$ sysctl net.inet.ip.portrange
```

* https://www.nginx.com/blog/inside-nginx-how-we-designed-for-performance-scale/
* Forward port 80 to 8080: http://apple.stackexchange.com/a/230331/52680

**Comment by ghprince** [comment]
@denji Thanks a lot for you clear explanation!
