### ISSUE TITLE
Error: The small-light setup script couldn't generate config file

### ISSUE THREAD

**Issue by eccentricyan** [Homebrew/homebrew-nginx#246]
### Indicate troubleshooting steps taken

- [ x ] Ran `brew update` and retried your prior step?
- [ x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x ] Checked that a similar issue hasn't already been filed?
- [ x ] Looked up the software bug tracker if reporting a build error?
- [ x ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
brew install nginx-full --with-image-filter --with-small-light-module

==> Installing nginx-full from homebrew/nginx
==> Downloading https://nginx.org/download/nginx-1.10.2.tar.gz
Already downloaded: /Users/shiyanhui/Library/Caches/Homebrew/nginx-full-1.10.2.tar.gz
==> ./setup
Error: The small-light setup script couldn't generate config file.
```

#### The complete command that you issued:
```
brew install nginx-full --with-image-filter --with-small-light-module
```
#### Gist with output of `brew doctor`:
```
Your system is ready to brew.
```
#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.1.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cce3414fbd39d146d97911dbb3bf07fffaa1080
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5bad66deb21aeecef875f9393c0707a115144956
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/shiyanhui/.anyenv/envs/rbenv/shims/ruby => /Users/shiyanhui/.anyenv/envs/rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_71
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: N/A
X11: N/A
```
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-nginx/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by denji** [comment]
brew remove small-light-nginx-module
brew reinstall nginx-full --with-image-filter --with-small-light-module

**Comment by eccentricyan** [comment]
@denji thank u!
