### ISSUE TITLE
Latest change to brew formula for openresty lost args that specified default config file location

### ISSUE THREAD

**Issue by rlamorea** [Homebrew/homebrew-nginx#248]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
Doing a brew update reinstalled openresty and it stopped using our config file.

While digging, found that the config file location changed from the default (for OS-X of `/usr/local/etc/openresty`.  The latest change to the openresty formula here:
https://github.com/Homebrew/homebrew-nginx/commit/ba2590172a8d5ce3e9e685ddb27bcd4ec577177a#diff-b167d823897bd58256f199b33127e112

Removes the arg for default config file location (among other things).

Was this intentional?  It doesn't seem like it should be.

**Comment by denji** [comment]
Bug #244
