### ISSUE TITLE
Request: add `--with-stream_proxy_module` to enable streaming support

### ISSUE THREAD

**Issue by quarryman** [Homebrew/homebrew-nginx#262]
ngx_stream_proxy_module is not among available options to build nginx with.
Add it plz

**Comment by denji** [comment]
`brew install nginx-full --with-stream`

**Comment by collinsethans** [comment]
Hi @denji, I built nginx 1.14.0 on linux with the option '--with-stream' to build ngx_stream_proxy_module. However, 'proxy_ssl' is still not recognized.

In your answer, did you mean that to have ngx_stream_proxy_module we should _also_ have --with-stream-geoip --with-stream-realip --with-stream-ssl --with-stream-ssl-preread?

Please clarify and let us know how to build in support for directive 'proxy_ssl'.

Best.

**Comment by denji** [comment]
```
brew install nginx-full --with-stream \
      --with-stream-ssl --with-stream-ssl-preread \
      --with-stream-realip
```

Can get the output of `nginx -V`?
P.S. `proxy_pass` can also use `https`.

**Comment by collinsethans** [comment]
Hi @denji, 

Here's the output you requested:
```

./objs/nginx -V
nginx version: nginx/1.14.0
built by gcc 4.9.2 (Debian 4.9.2-10+deb8u1) 
built with OpenSSL 1.1.0i  14 Aug 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx/nginx.pid --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/log/nginx/client_temp --http-proxy-temp-path=/var/log/nginx/proxy_temp --without-http_auth_basic_module --without-http_autoindex_module --without-http_memcached_module --without-http_referer_module --without-http_scgi_module --without-http_ssi_module --without-http_userid_module --without-http_uwsgi_module --without-select_module --with-http_realip_module --with-http_ssl_module --without-http_geo_module --with-pcre --without-http_mirror_module --without-http_split_clients_module --without-http_fastcgi_module --without-http_grpc_module --without-http_empty_gif_module --without-http_browser_module --without-http_upstream_hash_module --without-http_upstream_ip_hash_module --without-http_upstream_zone_module --without-stream_geo_module --without-stream_split_clients_module --without-stream_upstream_hash_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-threads --with-file-aio --with-http_v2_module --with-http_stub_status_module --with-openssl=/usr/local/src/openssl-1.1.0i --with-stream_ssl_module --with-stream
```

And here's the failure notice:
```
collinethan:/work/nginx-1.14.0$ sudo ./objs/nginx -t
nginx: [emerg] "proxy_ssl" directive is not allowed here in /etc/nginx/nginx.conf:345
nginx: configuration file /etc/nginx/nginx.conf test failed
```

At line 345 of nginx.conf, I have:
```
server {
    listen  443 ssl http2;
    server_name  www.snip.com;

    proxy_pass    off;             # <- line 345  Being explicitly with default proxy_pass
    ...
```

**Comment by denji** [comment]
> "proxy_ssl" directive is not allowed here

You added proxy_ssl other section.
* http://nginx.org/r/proxy_ssl

Context:	**stream**, **server**

**Comment by denji** [comment]
@collinsethans `server` section inside `stream` section?

stream {
....
    server {
      ...
    }
....
}

**Comment by collinsethans** [comment]
Hi @denji Sorry, I didn't quite understand. Yes, 'proxy_ssl' is in the context of server, as in the snippet I added at the end of my last msg.

Can you let me know what I need to do to have proxy_ssl in nginx.conf working?

**Comment by collinsethans** [comment]
Hi @denji 
No, my server section is not in stream section -- the nginx doc says it can be either in server or in stream, right?

**Comment by denji** [comment]
You do not quite understand, moudule stream is a separate subsystem, it can not be at the level of http->server. Just like the mail subsystem in http.
But if there is support for the stream-upstream in the module, you can also use it for stream inside upstream.

**Comment by collinsethans** [comment]
Thanks. I will dig deeper into this.
