### ISSUE TITLE
Location of modules subdirectory?

### ISSUE THREAD

**Issue by strife25** [Homebrew/homebrew-nginx#264]
Hello,

I am trying to load extra modules into my nguni configuration, but I am unable to figure out the path for the `load_module` rule. I have installed `nginx-full` with the following command:

`brew install nginx-full --with-gunzip --with-sub`

However, if I add a rule such as `gunzip on` to my config file, I get an error saying `unknown directive "gunzip"` in my `error.log` file (nginx is able to parse the config and startup fine).

After some research, it looks like I need to add a `load_module` rule to the main context of my config, but I am unable to determine the correct path for the modules because adding a rule such as:

`load_module "modules/http_gunzip_module.so";`

fails on my machine with the following result:

```
nginx: [emerg] dlopen() "/usr/local/Cellar/nginx-full/1.10.3/modules/http_gunzip_module.so" failed (dlopen(/usr/local/Cellar/nginx-full/1.10.3/modules/http_gunzip_module.so, 10): image not found) in
```

What is the correct path I am suppose to be using in order to enable the `gunzip` module?

Thank you!

**Comment by denji** [comment]
Dynamic recompilation modules #168 not ready
