### ISSUE TITLE
openresty-openssl should be keg only

### ISSUE THREAD

**Issue by felixbuenemann** [Homebrew/homebrew-nginx#295]
The formula `openresty-openssl` should be marked as `keg_only` so that is is not symlinked into `/usr/local`. This can be achieved by adding the following to the formula:

```ruby
keg_only "Only for use with OpenResty"
```

On my Mac installing ruby-2.4 with rvm failed to detect the homebrew openssl@1.1 install, because the openresty-openssl formula was symlinked and causing the version check in ruby's `configure` to fail.

**Comment by denji** [comment]
https://github.com/Homebrew/homebrew-nginx/commit/eb278d62640ad101038a058f017406c703f00901

**Comment by felixbuenemann** [comment]
@denji Do you think this change warrants a revision bump for the formula? By adding `revision 1` clients that do a homebrew upgrade would get the fix now instead of on the next openssl version bump. Of course they can also do `brew unlink openresty-openssl` to fix it.

**Comment by denji** [comment]
I can send a pull-request, well I will raise revision for rebuild.
