### ISSUE TITLE
patch SHA256 mismatch when install --with-lua-module

### ISSUE THREAD

**Issue by sernik** [Homebrew/homebrew-nginx#299]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
brew install nginx-full --with-lua-module
Updating Homebrew...
==> Installing nginx-full from homebrew/nginx
==> Installing dependencies for homebrew/nginx/nginx-full: lua-nginx-module
==> Installing homebrew/nginx/nginx-full dependency: lua-nginx-module
==> Downloading https://github.com/openresty/lua-nginx-module/archive/v0.10.8.tar.gz
Already downloaded: /Users/janek/Library/Caches/Homebrew/lua-nginx-module-0.10.8.tar.gz
==> Downloading https://github.com/openresty/lua-nginx-module/pull/1017.patch
==> Downloading from https://patch-diff.githubusercontent.com/raw/openresty/lua-nginx-module/pull/1017.patch
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 0ce12facbf3070f5fed58cae14f5e58c00803733e7e07fcd8577f901b45a17c9
Actual: 93e7bf4460668ad3e5fbfd39f4ca25d29bd7975864b7f42749f94b51346e5166
Archive: /Users/janek/Library/Caches/Homebrew/lua-nginx-module--patch-0ce12facbf3070f5fed58cae14f5e58c00803733e7e07fcd8577f901b45a17c9.patch
To retry an incomplete download, remove the file above.
```
#### Brief summary of issue:

Cannot install nginx-full with lua

#### The complete command that you issued:

`brew install nginx-full --with-lua-module`

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-nginx/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
Thanks for reporting this. This is the same problem as https://github.com/Homebrew/homebrew-core/pull/13792

**Comment by sernik** [comment]
Many thanks :-)
