### ISSUE TITLE
brew install nginx-full --with-upload-module fails with md5.h on OS X

### ISSUE THREAD

**Issue by dmaple** [Homebrew/homebrew-nginx#311]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
brew install nginx-full --with-upload-module --with-stream-ssl --with-headers-more-module --devel
==> Installing nginx-full from homebrew/nginx
==> Downloading https://nginx.org/download/nginx-1.13.3.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.13.3 --with-http_ssl_module --with-pcre --with-ipv6 --sbin-path=/usr/local/Cellar/nginx-full/1.13.3/bin/nginx --with-cc-opt=-I/usr/local/include -I/usr/local/opt/pcre/include -I/usr/local/opt/openssl/include --with-ld-opt=-L/usr/local/lib -L/usr/local/opt/pcre/lib -L/usr/local/opt/openssl/lib --conf-pa
==> make install
Last 15 lines from /Users/labuser/Library/Logs/Homebrew/nginx-full/02.make:
clang -c -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Wno-deprecated-declarations -Werror -g -I/usr/local/include -I/usr/local/opt/pcre/include -I/usr/local/opt/openssl/include -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \
		-o objs/ngx_modules.o \
		objs/ngx_modules.c
sed -e "s|%%PREFIX%%|/usr/local/Cellar/nginx-full/1.13.3|" \
		-e "s|%%PID_PATH%%|/usr/local/var/run/nginx.pid|" \
		-e "s|%%CONF_PATH%%|/usr/local/etc/nginx/nginx.conf|" \
		-e "s|%%ERROR_LOG_PATH%%|/usr/local/var/log/nginx/error.log|" \
		< man/nginx.8 > objs/nginx.8
/usr/local/share/upload-nginx-module/ngx_http_upload_module.c:14:10: fatal error: 'md5.h' file not found
#include <md5.h>
         ^~~~~~~
1 error generated.
make[1]: *** [objs/addon/upload-nginx-module/ngx_http_upload_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

#### Brief summary of issue:

Trying to install nginx with the upload module keeps failing even though I have openssl installed and I can find the header no problem.  It looks like for some reason the defines that upload-nginx-module use to enable openssl/md5.h instead of simply md5.h are not getting set.  The include paths listed are correct for openssl version of the md5.h .  I don't see a way to add extra options to the brew command line which would be passed to the compiler or configure app.

#### The complete command that you issued:
see above

I also tried this on two different Macs, both had the same issue.  One running 10.12.4 and the other 10.12.3

#### Gist with output of `brew doctor`:
some "Unexpected" libs and headers.  Nothing that looks like it would cause this issue

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/bce0c0e0183f959c89d340488edd0778

#### Output of `brew config`:
brew config
HOMEBREW_VERSION: 1.2.5-14-g88b762f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88b762f78447842a6187e0fda49c9493f029cbef
Last commit: 31 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ffa5a7ff463451d77837a69c978da319c8a81766
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 24-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.13.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 9.0
CLT: 8.2.0.0.1.1480973914
X11: N/A

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-nginx/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by denji** [comment]
https://github.com/vkholodkov/nginx-upload-module/pull/88

**Comment by denji** [comment]
https://github.com/Homebrew/homebrew-nginx/commit/0106bc3795509457bbe9c06667e6ac91deb92abf
