### ISSUE TITLE
Unknown directive `gzip_static`

### ISSUE THREAD

**Issue by christopherhein** [Homebrew/homebrew-nginx#64]
When using `gzip_static on;` in the nginx.conf you get:

```
nginx: [emerg] unknown directive "gzip_static"
```

But it appears the `nginx-full.rb` https://github.com/Homebrew/homebrew-nginx/blob/master/nginx-full.rb#L33 that it's a core module?

Am I missing something when trying to install?

Thanks!

**Comment by acrolink** [comment]
The accurate and working directive is `--with-http_gzip_static_module`

**Comment by denji** [comment]
@acrolink `brew install nginx-full --with-gzip-static`: https://github.com/Homebrew/homebrew-nginx/blob/40a68dd/Formula/nginx-full.rb#L25
