### ISSUE TITLE
"server" directive is not allowed here

### ISSUE THREAD

**Issue by michaellopez** [Homebrew/homebrew-nginx#92]
On a fresh Yosemite I get this error:

`nginx: [emerg] "server" directive is not allowed here in /usr/local/etc/nginx/servers/myserver:1`

Found [this](http://serverfault.com/questions/466486/nginx-server-directive-is-not-allowed-here) thread at serverfault and moving the `include` statement [here](https://github.com/Homebrew/homebrew-nginx/blob/master/Formula/nginx-full.rb#L161) to inside `http` clause makes it work.

**Comment by message** [comment]
+1
