### ISSUE TITLE
nginx-full with LDAP ld error (OS X 10.10.3)

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-nginx#93]
_From @jesse-gallagher on May 18, 2015 13:53_

I've run into trouble trying to install nginx-full with the auth-ldap module, specifically encountering this error near the end:

	Undefined symbols for architecture x86_64:
	  "_ber_sockbuf_add_io", referenced from:
	      _ngx_http_auth_ldap_connection_established in ngx_http_auth_ldap_module.o

I've tried a number of troubleshooting techniques I've seen with similar problems - re-running xcode-select, reinstalling the openldap package, `brew update`, and a couple others, though my inexperience in these matters means I'm not sure if I'm following the right paths. I've tried including --HEAD in the command, but that fails with this same problem.

It looks like there exist libldap.dylib (and similar) files in both /usr/lib and /usr/local/lib, all of which include x86_64.

The specific command I'm executing is `brew install nginx-full --with-auth-ldap-module -v` and I've created a Gist of the four log files, the last bit of the output here, and the listings of the ldap lib files here: https://gist.github.com/jesse-gallagher/53d7f33ab1e4d757198b

If there's any other useful information I can cull, I'll be glad to track it down.

_Copied from original issue: Homebrew/homebrew#39873_

**Comment by jesse-gallagher** [comment]
In case it's useful, based on the comment on the pre-moved issue, nm reports these for the two sets of files (with warnings from inapplicable files removed):

	$ nm -o /usr/lib/*ldap* | grep ber_sockbuf_add_io
	/usr/lib/libldap.dylib: 0000000000006073 T _ber_sockbuf_add_io
	/usr/lib/libldap_r.dylib: 0000000000006073 T _ber_sockbuf_add_io

	$ nm -o /usr/local/lib/*ldap* | grep ber_sockbuf_add_io
	/usr/local/lib/libldap-2.4.2.10.2.dylib:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap-2.4.2.dylib:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap.a:open.o:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap.a:sasl.o:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap.a:tls2.o:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap.dylib:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap_r-2.4.2.10.2.dylib:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap_r-2.4.2.dylib:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap_r.a:open.o:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap_r.a:sasl.o:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap_r.a:tls2.o:                  U _ber_sockbuf_add_io
	/usr/local/lib/libldap_r.dylib:                  U _ber_sockbuf_add_io

**Comment by denji** [comment]
@jesse-gallagher Fixed https://github.com/Homebrew/homebrew-nginx/commit/7298591ff3ef1e00042ef4dff8f0777535e09b22.

**Comment by jesse-gallagher** [comment]
Looks like it builds properly for me now - thanks!
